# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cc/zkTransformer/3rd/hyrax-bls12-381

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cc/zkTransformer/3rd/hyrax-bls12-381

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cc/zkTransformer/3rd/hyrax-bls12-381/CMakeFiles /home/cc/zkTransformer/3rd/hyrax-bls12-381/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cc/zkTransformer/3rd/hyrax-bls12-381/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hyrax_time

# Build rule for target.
hyrax_time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyrax_time
.PHONY : hyrax_time

# fast build rule for target.
hyrax_time/fast:
	$(MAKE) -f src/CMakeFiles/hyrax_time.dir/build.make src/CMakeFiles/hyrax_time.dir/build
.PHONY : hyrax_time/fast

#=============================================================================
# Target rules for targets named hyrax_lib

# Build rule for target.
hyrax_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyrax_lib
.PHONY : hyrax_lib

# fast build rule for target.
hyrax_lib/fast:
	$(MAKE) -f src/CMakeFiles/hyrax_lib.dir/build.make src/CMakeFiles/hyrax_lib.dir/build
.PHONY : hyrax_lib/fast

#=============================================================================
# Target rules for targets named mclbn384_256

# Build rule for target.
mclbn384_256: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mclbn384_256
.PHONY : mclbn384_256

# fast build rule for target.
mclbn384_256/fast:
	$(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384_256.dir/build.make 3rd/mcl/CMakeFiles/mclbn384_256.dir/build
.PHONY : mclbn384_256/fast

#=============================================================================
# Target rules for targets named mclbn384

# Build rule for target.
mclbn384: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mclbn384
.PHONY : mclbn384

# fast build rule for target.
mclbn384/fast:
	$(MAKE) -f 3rd/mcl/CMakeFiles/mclbn384.dir/build.make 3rd/mcl/CMakeFiles/mclbn384.dir/build
.PHONY : mclbn384/fast

#=============================================================================
# Target rules for targets named mclbn256

# Build rule for target.
mclbn256: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mclbn256
.PHONY : mclbn256

# fast build rule for target.
mclbn256/fast:
	$(MAKE) -f 3rd/mcl/CMakeFiles/mclbn256.dir/build.make 3rd/mcl/CMakeFiles/mclbn256.dir/build
.PHONY : mclbn256/fast

#=============================================================================
# Target rules for targets named msm_avx.o

# Build rule for target.
msm_avx.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msm_avx.o
.PHONY : msm_avx.o

# fast build rule for target.
msm_avx.o/fast:
	$(MAKE) -f 3rd/mcl/CMakeFiles/msm_avx.o.dir/build.make 3rd/mcl/CMakeFiles/msm_avx.o.dir/build
.PHONY : msm_avx.o/fast

#=============================================================================
# Target rules for targets named mcl_st

# Build rule for target.
mcl_st: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcl_st
.PHONY : mcl_st

# fast build rule for target.
mcl_st/fast:
	$(MAKE) -f 3rd/mcl/CMakeFiles/mcl_st.dir/build.make 3rd/mcl/CMakeFiles/mcl_st.dir/build
.PHONY : mcl_st/fast

#=============================================================================
# Target rules for targets named mcl

# Build rule for target.
mcl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcl
.PHONY : mcl

# fast build rule for target.
mcl/fast:
	$(MAKE) -f 3rd/mcl/CMakeFiles/mcl.dir/build.make 3rd/mcl/CMakeFiles/mcl.dir/build
.PHONY : mcl/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hyrax_time"
	@echo "... hyrax_lib"
	@echo "... mclbn384_256"
	@echo "... mclbn384"
	@echo "... mclbn256"
	@echo "... msm_avx.o"
	@echo "... mcl_st"
	@echo "... mcl"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

